language: python

python:
- '2.7'
- '3.6'
- '3.7'
- '3.8'

sudo: false

env:
  PYTHONPATH: resources/lib:test
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

script:
- tox
- tox -e flake8
- pylint screensaver.py
#- msgcmp resources/language/resource.language.{nl_nl,en_gb}/strings.po
#- kodi-addon-checker . --branch=krypton
#- kodi-addon-checker . --branch=leia
- coverage run -m unittest discover
- coverage run -a screensaver.py

after_success:
- codecov
